### ISSUE TITLE
Memory error when running Image_handler.py on Windows

### ISSUE THREAD

**Issue by y1huac00** [H-Jamieu/SummerProject#1]
Hi Jiamian,
When I tried to run Image_handler.py on Windows, a "memory error" poped out at the middle of running. I guess that too many images have been saved to the variable 'images'.
![MIXJ$VND(AEZ7H$)1{AX`HL](https://user-images.githubusercontent.com/63455355/123276710-0002cb00-d538-11eb-9b64-444184b6e5b7.png)
![TR6B_4G K(V_ZO )AK}6F 8](https://user-images.githubusercontent.com/63455355/123276747-098c3300-d538-11eb-9052-d12198ed6916.png)

I am not sure why MacOS could avoid this situation. Have you tried on Windows? If this problem remains, maybe we can modify the code to avoid reading all images at once. For example, to read and crop 1000 images at one time, etc.

**Comment by H-Jamieu** [comment]
Fixed. You can try new version now.

**Comment by y1huac00** [comment]
Thanks!
